services:
  drupal:
    volumes:
      - drupal_sites:/opt/drupal/web/sites
      - drupal_profiles:/opt/drupal/web/profiles
      - drupal_modules:/opt/drupal/web/modules
      - ./volumes/drupal-modules/site:/opt/drupal/web/sites/default/modules
      - ./volumes/drupal-themes:/opt/drupal/web/sites/default/themes
      - ./volumes/civicrm-extensions:/opt/drupal/web/sites/default/files/civicrm/ext

volumes:
  drupal_profiles:
  drupal_sites:
  drupal_modules: