services:
  drupal:
    build:
      context: ./docker/drupal
      args:
        - PHP_VERSION=${PHP_VERSION}
        - CIVICRM_VERSION=${CIVICRM_VERSION}
        - WEBFORM_VERSION=${WEBFORM_VERSION}
        - WEBFORM_CIVICRM_VERSION=${WEBFORM_CIVICRM_VERSION}
        - WEBFORM_VALIDATION_VERSION=${WEBFORM_VALIDATION_VERSION}
    restart: always
    networks:
      - mariadb
    environment:
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DRUPAL_HOST
      - DRUPAL_USER
      - DRUPAL_PASSWORD

networks:
  mariadb:
    name: mariadb
    external: true