services:
  drupal:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.service=${TRAEFIK_SERVICE}"
      - "traefik.http.services.${TRAEFIK_SERVICE}.loadbalancer.server.port=80"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.entrypoints=${TRAEFIK_ENTRYPOINTS}"
      - "${TRAEFIK_CERTRESOLVER_LABEL}"
    networks:
      - mariadb
      - traefik

networks:
  mariadb:
    name: mariadb
    external: true
  traefik:
    name: traefik
    external: true