#!/usr/bin/env bash
set -e

echo "Installing PHPUnit"

composer require --dev phpunit/phpunit ^9

echo "Configuring the test database"

pushd /var/www
    php cv-configure.php > .cv.json
    chown www-data .cv.json
popd